/**
 * Dữ liệu catalog thật của TechPhone Store.
 *
 * `price` là giá bán hiện tại, `oldPrice` là giá niêm yết trước giảm — seed sẽ tự
 * tính `discountPercent`. Các thông số dùng để lọc (ram/storage/screen/battery)
 * phải nằm phẳng ở cấp cao nhất vì trang Điện thoại đọc trực tiếp `product.ram`,
 * `product.storage` và `Number.parseInt(product.battery)`; object `specifications`
 * chỉ dùng để hiển thị ở trang chi tiết.
 *
 * `imageSlug` trỏ tới bộ ảnh trong `backend/uploads/catalog/<imageSlug>-<n>.<ext>`.
 * Sản phẩm chưa có ảnh thật thì bỏ trống, seed sẽ dùng ảnh giữ chỗ.
 */

const phones = [
  {
    id: 'phone-1',
    name: 'iPhone 16 Pro Max',
    brand: 'Apple',
    imageSlug: 'phone-iphone-16-pro-max',
    price: 33990000,
    oldPrice: 34990000,
    stock: 25,
    ram: '8GB',
    storage: '256GB',
    screen: '6.9 inch, Super Retina XDR OLED, 120Hz ProMotion, 2000 nits',
    chip: 'Apple A18 Pro 6 nhân',
    battery: '4685 mAh, Sạc nhanh 25W MagSafe / PD',
    camera: 'Chính 48MP, Siêu rộng 48MP, Tele 12MP (Zoom quang 5x)',
    frontCamera: '12MP TrueDepth',
    material: 'Khung viền Titan cấp 5, Mặt lưng kính mờ nhám',
    os: 'iOS 18',
  },
  {
    id: 'phone-2',
    name: 'iPhone 16 Pro',
    brand: 'Apple',
    imageSlug: 'phone-iphone-16-pro',
    price: 28990000,
    oldPrice: 29990000,
    stock: 20,
    ram: '8GB',
    storage: '128GB',
    screen: '6.3 inch, Super Retina XDR OLED, 120Hz ProMotion',
    chip: 'Apple A18 Pro',
    battery: '3582 mAh, Sạc nhanh PD',
    camera: 'Chính 48MP & Phụ 48MP, 12MP (Zoom quang 5x)',
    frontCamera: '12MP',
    material: 'Khung Titan, Mặt kính Ceramic Shield',
    os: 'iOS 18',
  },
  {
    id: 'phone-3',
    name: 'iPhone 16 Plus',
    brand: 'Apple',
    imageSlug: 'phone-iphone-16-plus',
    price: 24990000,
    oldPrice: 25990000,
    stock: 19,
    ram: '8GB',
    storage: '128GB',
    screen: '6.7 inch, Super Retina XDR OLED, 60Hz',
    chip: 'Apple A18',
    battery: '4674 mAh, Sạc nhanh 20W',
    camera: 'Chính 48MP & Phụ 12MP',
    frontCamera: '12MP',
    material: 'Khung nhôm chuẩn hàng không vũ trụ, Mặt lưng kính pha màu',
    os: 'iOS 18',
  },
  {
    id: 'phone-4',
    name: 'iPhone 16',
    brand: 'Apple',
    imageSlug: 'phone-iphone-16',
    price: 21990000,
    oldPrice: 22990000,
    stock: 30,
    ram: '8GB',
    storage: '128GB',
    screen: '6.1 inch, Super Retina XDR OLED, 60Hz',
    chip: 'Apple A18',
    battery: '3561 mAh, Sạc nhanh 20W',
    camera: 'Chính 48MP & Phụ 12MP',
    frontCamera: '12MP',
    material: 'Khung nhôm, Mặt kính pha màu',
    os: 'iOS 18',
  },
  {
    id: 'phone-5',
    name: 'Galaxy S25 Ultra',
    brand: 'Samsung',
    imageSlug: 'phone-galaxy-s25-ultra',
    price: 30990000,
    oldPrice: 33990000,
    stock: 47,
    ram: '12GB',
    storage: '256GB',
    screen: '6.8 inch, Dynamic AMOLED 2X, QHD+, 120Hz, 2600 nits',
    chip: 'Snapdragon 8 Elite for Galaxy',
    battery: '5000 mAh, Sạc nhanh 45W',
    camera: 'Chính 200MP & Phụ 50MP, 50MP, 10MP',
    frontCamera: '12MP',
    material: 'Khung Titan, Kính Corning Gorilla Armor chống lóa',
    os: 'One UI 7 (Android 15)',
  },
  {
    id: 'phone-6',
    name: 'Galaxy S25 Plus',
    brand: 'Samsung',
    imageSlug: 'phone-galaxy-s25-plus',
    price: 23990000,
    oldPrice: 25990000,
    stock: 30,
    ram: '12GB',
    storage: '256GB',
    screen: '6.7 inch, Dynamic AMOLED 2X, QHD+, 120Hz',
    chip: 'Snapdragon 8 Elite',
    battery: '4900 mAh, Sạc nhanh 45W',
    camera: 'Chính 50MP, Siêu rộng 12MP, Tele 10MP',
    frontCamera: '12MP',
    material: 'Khung Armor Aluminum, Kính Gorilla Glass Victus 2',
    os: 'One UI 7 (Android 15)',
  },
  {
    id: 'phone-7',
    name: 'Galaxy S25',
    brand: 'Samsung',
    imageSlug: 'phone-galaxy-s25',
    price: 19990000,
    oldPrice: 21990000,
    stock: 30,
    ram: '12GB',
    storage: '128GB',
    screen: '6.2 inch, Dynamic AMOLED 2X, FHD+, 120Hz',
    chip: 'Snapdragon 8 Elite',
    battery: '4000 mAh, Sạc nhanh 25W',
    camera: 'Chính 50MP, Siêu rộng 12MP, Tele 10MP',
    frontCamera: '12MP',
    material: 'Khung Armor Aluminum',
    os: 'One UI 7 (Android 15)',
  },
  {
    id: 'phone-8',
    name: 'Galaxy Z Fold6',
    brand: 'Samsung',
    imageSlug: 'phone-galaxy-z-fold6',
    price: 38990000,
    oldPrice: 43990000,
    stock: 32,
    ram: '12GB',
    storage: '256GB',
    screen: 'Chính 7.6 inch & Phụ 6.3 inch, Dynamic AMOLED 2X 120Hz',
    chip: 'Snapdragon 8 Gen 3 for Galaxy',
    battery: '4400 mAh, Sạc nhanh 25W',
    camera: 'Chính 50MP, Siêu rộng 12MP, Tele 10MP',
    frontCamera: '4MP (dưới màn hình) & 10MP (màn phụ)',
    material: 'Bản lề rãnh kép Flex Hinge, Khung Armor Aluminum',
    os: 'Android 14',
  },
  {
    id: 'phone-9',
    name: 'Galaxy Z Flip6',
    brand: 'Samsung',
    imageSlug: 'phone-galaxy-z-flip6',
    price: 20990000,
    oldPrice: 24990000,
    stock: 29,
    ram: '12GB',
    storage: '256GB',
    screen: 'Chính 6.7 inch FHD+ 120Hz & Phụ Flex Window 3.4 inch Super AMOLED',
    chip: 'Snapdragon 8 Gen 3 for Galaxy',
    battery: '4000 mAh, Sạc 25W',
    camera: 'Chính 50MP & Phụ 12MP',
    frontCamera: '10MP',
    material: 'Khung nhôm, Kính Gorilla Glass Victus 2',
    os: 'Android 14',
  },
  {
    id: 'phone-10',
    name: 'Galaxy A56 5G',
    brand: 'Samsung',
    imageSlug: 'phone-galaxy-a56',
    price: 9990000,
    oldPrice: 10990000,
    stock: 38,
    ram: '8GB',
    storage: '128GB',
    screen: '6.6 inch, Super AMOLED, FHD+, 120Hz',
    chip: 'Exynos 1580',
    battery: '5000 mAh, Sạc nhanh 45W',
    camera: 'Chính 50MP OIS, Siêu rộng 12MP, Macro 5MP',
    frontCamera: '32MP',
    material: 'Khung kim loại Key Island, Kháng nước IP67',
    os: 'Android 15',
  },
  {
    id: 'phone-11',
    name: 'Xiaomi 15 Ultra',
    brand: 'Xiaomi',
    imageSlug: 'phone-xiaomi-15-ultra',
    price: 29990000,
    oldPrice: 31990000,
    stock: 50,
    ram: '16GB',
    storage: '512GB',
    screen: '6.73 inch, LTPO AMOLED 2K+, 120Hz, 3200 nits',
    chip: 'Snapdragon 8 Elite',
    battery: '6000 mAh, Sạc nhanh 90W có dây, 80W không dây',
    camera: 'Cụm 4 camera Leica 50MP + 200MP tiềm vọng (Cảm biến 1 inch)',
    frontCamera: '32MP',
    material: 'Khung hợp kim nhôm / Da sinh học Nano thế hệ mới',
    os: 'Xiaomi HyperOS 2',
  },
  {
    id: 'phone-12',
    name: 'Xiaomi 15',
    brand: 'Xiaomi',
    imageSlug: 'phone-xiaomi-15',
    price: 21990000,
    oldPrice: 23990000,
    stock: 10,
    ram: '12GB',
    storage: '256GB',
    screen: '6.36 inch, OLED 1.5K, 120Hz',
    chip: 'Snapdragon 8 Elite',
    battery: '5400 mAh, Sạc nhanh 90W',
    camera: '3 ống kính Leica 50MP',
    frontCamera: '32MP',
    material: 'Khung nhôm nguyên khối, Kính Dragon Crystal',
    os: 'Xiaomi HyperOS 2',
  },
  {
    id: 'phone-13',
    name: 'Xiaomi 14T Pro',
    brand: 'Xiaomi',
    imageSlug: 'phone-xiaomi-14t-pro',
    price: 15990000,
    oldPrice: 16990000,
    stock: 20,
    ram: '12GB',
    storage: '512GB',
    screen: '6.67 inch, AMOLED 1.5K, 144Hz',
    chip: 'MediaTek Dimensity 9300+',
    battery: '5000 mAh, Sạc nhanh HyperCharge 120W',
    camera: 'Leica 50MP Light Fusion 900, Tele 50MP, Siêu rộng 12MP',
    frontCamera: '32MP',
    material: 'Khung kim loại, Chuẩn kháng nước bụi IP68',
    os: 'Xiaomi HyperOS',
  },
  {
    id: 'phone-14',
    name: 'Redmi Note 14 Pro+',
    brand: 'Xiaomi',
    imageSlug: 'phone-redmi-note-14-pro-plus',
    price: 10990000,
    oldPrice: 11490000,
    stock: 29,
    ram: '12GB',
    storage: '256GB',
    screen: '6.67 inch, OLED cong 1.5K, 120Hz, 3000 nits',
    chip: 'Snapdragon 7s Gen 3',
    battery: '6200 mAh, Sạc nhanh 90W',
    camera: 'Chính 50MP Light Hunter 800, Tele 50MP, Góc rộng 8MP',
    frontCamera: '20MP',
    material: 'Kính cường lực Gorilla Glass Victus 2, IP68/IP69K',
    os: 'Xiaomi HyperOS',
  },
  {
    id: 'phone-15',
    name: 'Redmi Note 14',
    brand: 'Xiaomi',
    imageSlug: 'phone-redmi-note-14',
    price: 5990000,
    oldPrice: 6490000,
    stock: 30,
    ram: '6GB',
    storage: '128GB',
    screen: '6.67 inch, OLED FHD+, 120Hz',
    chip: 'Dimensity 7025 Ultra',
    battery: '5110 mAh, Sạc nhanh 45W',
    camera: 'Chính 50MP Sony LYT-600 OIS & Phụ 2MP',
    frontCamera: '16MP',
    material: 'Khung nhựa, Kính Gorilla Glass 5',
    os: 'Xiaomi HyperOS',
  },
  {
    id: 'phone-16',
    name: 'OPPO Find X8 Pro',
    brand: 'OPPO',
    imageSlug: 'phone-oppo-find-x8-pro',
    price: 27990000,
    oldPrice: 29990000,
    stock: 38,
    ram: '16GB',
    storage: '512GB',
    screen: '6.78 inch, LTPO AMOLED 1.5K, 120Hz',
    chip: 'MediaTek Dimensity 9400',
    battery: '5910 mAh Glacier Battery, Sạc nhanh SuperVOOC 80W',
    camera: 'Cụm 4 camera Hasselblad 50MP (Kép tiềm vọng 3x & 6x)',
    frontCamera: '32MP',
    material: 'Mặt lưng kính vân mây nhung, Kháng nước IP68/IP69',
    os: 'ColorOS 15',
  },
  {
    id: 'phone-17',
    name: 'OPPO Reno13 Pro',
    brand: 'OPPO',
    imageSlug: 'phone-oppo-reno13-pro',
    price: 16990000,
    oldPrice: 17990000,
    stock: 45,
    ram: '12GB',
    storage: '256GB',
    screen: '6.83 inch, OLED cong 4 cạnh 1.5K, 120Hz',
    chip: 'Dimensity 8350',
    battery: '5800 mAh, Sạc nhanh 80W SuperVOOC',
    camera: 'Chính 50MP Sony OIS, Tele tiềm vọng 50MP, Siêu rộng 8MP',
    frontCamera: '50MP AF',
    material: 'Khung hợp kim nhôm, Kháng nước IP69',
    os: 'ColorOS 15',
  },
  {
    id: 'phone-18',
    name: 'OPPO A5 Pro',
    brand: 'OPPO',
    imageSlug: 'phone-oppo-a5-pro',
    price: 6990000,
    oldPrice: 7490000,
    stock: 15,
    ram: '8GB',
    storage: '256GB',
    screen: '6.7 inch, OLED cong FHD+, 120Hz',
    chip: 'Dimensity 7300',
    battery: '5800 mAh, Sạc nhanh 45W SuperVOOC',
    camera: 'Chính 50MP & Phụ 2MP',
    frontCamera: '16MP',
    material: 'Khung gia cố chống sốc quân đội 360 độ, Kháng nước IP69',
    os: 'ColorOS 15',
  },
  {
    id: 'phone-19',
    name: 'vivo X200 Pro',
    brand: 'vivo',
    imageSlug: '',
    price: 25990000,
    oldPrice: 27990000,
    stock: 25,
    ram: '16GB',
    storage: '512GB',
    screen: '6.78 inch, LTPO AMOLED 1.5K, 120Hz, 4500 nits',
    chip: 'MediaTek Dimensity 9400',
    battery: '6000 mAh BlueOcean, Sạc FlashCharge 90W',
    camera: 'Ống kính Zeiss 50MP chính LYT-818 & 200MP Tele tiềm vọng Zeiss APO',
    frontCamera: '32MP',
    material: 'Kính Armor Glass, Kháng nước chuẩn IP68 & IP69',
    os: 'OriginOS 5 / Funtouch OS 15',
  },
  {
    id: 'phone-20',
    name: 'vivo V50',
    brand: 'vivo',
    imageSlug: '',
    price: 12990000,
    oldPrice: 13990000,
    stock: 30,
    ram: '12GB',
    storage: '256GB',
    screen: '6.78 inch, AMOLED cong 1.5K, 120Hz',
    chip: 'Snapdragon 7 Gen 3',
    battery: '5500 mAh, Sạc nhanh FlashCharge 80W',
    camera: 'Chính 50MP OIS Zeiss & 50MP Siêu rộng, Đèn vòng Aura Light',
    frontCamera: '50MP Eye-AF',
    material: 'Mặt lưng kính vân kim sa, Thiết kế siêu mỏng',
    os: 'Funtouch OS 15',
  },
  {
    id: 'phone-21',
    name: 'HONOR Magic7 Pro',
    brand: 'Honor',
    imageSlug: 'phone-honor-magic7-pro',
    price: 24990000,
    oldPrice: 26990000,
    stock: 42,
    ram: '12GB',
    storage: '512GB',
    screen: '6.8 inch, LTPO OLED 1.5K, 120Hz, Tần số xung PWM 4320Hz',
    chip: 'Snapdragon 8 Elite',
    battery: '5850 mAh Silicon-Carbon, Sạc nhanh 100W có dây, 80W không dây',
    camera: 'Chính 50MP thay đổi khẩu độ, Tele tiềm vọng 200MP, Siêu rộng 50MP',
    frontCamera: '50MP + Cảm biến 3D ToF',
    material: 'Kính chống va đập Giant Rhinoceros Glass, IP68/IP69',
    os: 'MagicOS 9.0',
  },
  {
    id: 'phone-22',
    name: 'HONOR 400 Pro',
    brand: 'Honor',
    imageSlug: 'phone-honor-400-pro',
    price: 16990000,
    oldPrice: 17990000,
    stock: 50,
    ram: '12GB',
    storage: '512GB',
    screen: '6.78 inch, AMOLED 1.5K, 120Hz',
    chip: 'Snapdragon 8 Gen 3',
    battery: '5300 mAh, Sạc nhanh 100W',
    camera: 'Chính 50MP Studio Harcourt Paris, Tele 50MP OIS, Góc rộng 12MP',
    frontCamera: '50MP AF',
    material: 'Lưng kính vân nghệ thuật, Viền mỏng',
    os: 'MagicOS 9.0',
  },
  {
    id: 'phone-23',
    name: 'realme GT 7 Pro',
    brand: 'realme',
    imageSlug: '',
    price: 18990000,
    oldPrice: 20990000,
    stock: 25,
    ram: '12GB',
    storage: '256GB',
    screen: '6.78 inch, Eco² OLED Plus 1.5K, 120Hz, Độ sáng 6000 nits',
    chip: 'Snapdragon 8 Elite',
    battery: '6500 mAh Titan Battery, Sạc nhanh SuperVOOC 120W',
    camera: 'Chính 50MP Sony IMX906 OIS, Tele tiềm vọng 50MP Sony LYT-600, Góc rộng 8MP',
    frontCamera: '16MP',
    material: 'Thiết kế cảm hứng Sao Hỏa (Mars Design), Chuẩn kháng nước IP69',
    os: 'Realme UI 6.0',
  },
  {
    id: 'phone-24',
    name: 'realme 14 Pro+',
    brand: 'realme',
    imageSlug: '',
    price: 11990000,
    oldPrice: 12990000,
    stock: 28,
    ram: '12GB',
    storage: '256GB',
    screen: '6.7 inch, OLED cong 120Hz',
    chip: 'Snapdragon 7s Gen 3',
    battery: '5500 mAh, Sạc nhanh 80W',
    camera: 'Chính 50MP OIS & Tele tiềm vọng 50MP Zoom quang 3x',
    frontCamera: '32MP',
    material: 'Lưng da thuần chay phối màu cao cấp',
    os: 'Realme UI 6.0',
  },
  {
    id: 'phone-25',
    name: 'Google Pixel 9 Pro',
    brand: 'Google',
    imageSlug: 'phone-pixel-9-pro',
    price: 23990000,
    oldPrice: 25990000,
    stock: 37,
    ram: '16GB',
    storage: '128GB',
    screen: '6.3 inch, Super Actua LTPO OLED, 120Hz, 3000 nits',
    chip: 'Google Tensor G4 kèm chip bảo mật Titan M2',
    battery: '4700 mAh, Sạc nhanh 27W, Sạc không dây Pixel Stand',
    camera: 'Chính 50MP Octa PD, Siêu rộng 48MP Quad PD, Tele 48MP 5x',
    frontCamera: '42MP Dual PD tự động lấy nét',
    material: 'Thanh camera kim loại nguyên khối, Kính Corning Gorilla Glass Victus 2',
    os: 'Android 15 gốc hỗ trợ cập nhật 7 năm',
  },
];

const accessories = [
  {
    id: 'accessory-1',
    name: 'Tai nghe không dây Apple AirPods Pro 2 (Cổng sạc USB-C)',
    brand: 'Apple',
    category: 'Tai nghe',
    imageSlug: 'acc-airpods-pro-2',
    price: 5490000,
    oldPrice: 6190000,
    stock: 40,
    specifications: {
      'Loại phụ kiện': 'Tai nghe True Wireless',
      'Kết nối': 'Bluetooth 5.3, Chip H2',
      'Thời lượng pin': '6 giờ nghe liên tục (Tổng 30 giờ kèm hộp sạc)',
      'Tính năng': 'Chống ồn chủ động ANC thế hệ 2, Xuyên âm thông minh, Hộp sạc tích hợp loa tìm kiếm và chuẩn kháng nước IP54',
    },
  },
  {
    id: 'accessory-2',
    name: 'Tai nghe không dây Samsung Galaxy Buds3 Pro',
    brand: 'Samsung',
    category: 'Tai nghe',
    imageSlug: 'acc-galaxy-buds3-pro',
    price: 4790000,
    oldPrice: 5490000,
    stock: 30,
    specifications: {
      'Loại phụ kiện': 'Tai nghe True Wireless',
      'Kết nối': 'Bluetooth 5.4, Bộ giải mã SSC HiFi 24bit/96kHz',
      'Thời lượng pin': '7 giờ nghe (30 giờ với hộp)',
      'Tính năng': 'Dải đèn LED Blade Lights tùy biến, Chống ồn thích ứng AI, Kháng nước IP57',
    },
  },
  {
    id: 'accessory-3',
    name: 'Củ sạc Anker GaNPrime 67W 3 cổng A2668',
    brand: 'Anker',
    category: 'Sạc',
    imageSlug: '',
    price: 890000,
    oldPrice: 1200000,
    stock: 60,
    specifications: {
      'Loại phụ kiện': 'Củ sạc nhanh',
      'Cổng kết nối': '2 cổng USB-C, 1 cổng USB-A',
      'Công suất tối đa': '67W Max (PowerIQ 4.0 & Dynamic Power Distribution)',
      'Tương thích': 'iPhone 16 series, Galaxy S25 series, MacBook, iPad, Laptop Type-C',
      'Tính năng': 'Công nghệ tản nhiệt ActiveShield 2.0, chân gập 90 độ tiện lợi',
    },
  },
  {
    id: 'accessory-4',
    name: 'Pin dự phòng Baseus Blade HD 100W 20.000mAh',
    brand: 'Baseus',
    category: 'Pin dự phòng',
    imageSlug: '',
    price: 1450000,
    oldPrice: 1800000,
    stock: 35,
    specifications: {
      'Loại phụ kiện': 'Sạc dự phòng công suất lớn',
      'Dung lượng': '20.000 mAh',
      'Công suất tối đa': '100W Power Delivery',
      'Tương thích': 'Sạc được cho cả Laptop, MacBook, Steam Deck, Điện thoại',
      'Tính năng': 'Thiết kế siêu mỏng dạng dẹt chỉ 18mm, màn hình hiển thị công suất thực',
    },
  },
  {
    id: 'accessory-5',
    name: 'Củ sạc Apple 20W USB-C Chính Hãng',
    brand: 'Apple',
    category: 'Sạc',
    imageSlug: 'acc-apple-20w',
    price: 490000,
    oldPrice: 550000,
    stock: 120,
    specifications: {
      'Loại phụ kiện': 'Củ sạc nhanh',
      'Cổng kết nối': '1 cổng USB-C',
      'Công suất tối đa': '20W (Power Delivery 3.0)',
      'Tương thích': 'Tối ưu cho toàn bộ dòng iPhone và iPad',
      'Tính năng': 'Chống quá nhiệt, tự điều chỉnh dòng điện tiêu chuẩn Apple',
    },
  },
  {
    id: 'accessory-6',
    name: 'Củ sạc Samsung 45W Type-C Super Fast Charging',
    brand: 'Samsung',
    category: 'Sạc',
    imageSlug: '',
    price: 750000,
    oldPrice: 890000,
    stock: 75,
    specifications: {
      'Loại phụ kiện': 'Củ sạc nhanh',
      'Cổng kết nối': '1 cổng USB-C',
      'Công suất tối đa': '45W (Chuẩn PPS / PD 3.0)',
      'Tương thích': 'Galaxy S25 Ultra, S24 Ultra, Tab S9 Series, Laptop văn phòng',
      'Tính năng': 'Kèm sẵn dây cáp 5A C-to-C bọc dày chống đứt',
    },
  },
  {
    id: 'accessory-7',
    name: 'Pin dự phòng Anker MagGo 10.000mAh Sạc Không Dây Qi2 15W A1654',
    brand: 'Anker',
    category: 'Pin dự phòng',
    imageSlug: '',
    price: 1190000,
    oldPrice: 1450000,
    stock: 50,
    specifications: {
      'Loại phụ kiện': 'Sạc dự phòng không dây nam châm',
      'Dung lượng': '10.000 mAh (Lõi pin Polymer)',
      'Công suất tối đa': 'Không dây chuẩn Qi2 15W, Cổng Type-C 27W',
      'Tương thích': 'iPhone có MagSafe, AirPods, smartphone hỗ trợ sạc chuẩn Qi',
      'Tính năng': 'Màn hình kỹ thuật số hiển thị phần trăm pin và thời gian sạc, chân chống gập đa năng',
    },
  },
  {
    id: 'accessory-8',
    name: 'Cáp sạc C to C Apple Woven 60W (1m)',
    brand: 'Apple',
    category: 'Sạc',
    imageSlug: 'acc-apple-cable-60w',
    price: 520000,
    oldPrice: 590000,
    stock: 80,
    specifications: {
      'Loại phụ kiện': 'Dây cáp sạc',
      'Chiều dài': '1 mét',
      'Công suất tối đa': '60W Max',
      'Chất liệu': 'Dây dù bện bọc sợi cao cấp chống rối và đứt gãy',
      'Tương thích': 'iPhone 15/16 Series, iPad Pro, MacBook Air',
    },
  },
  {
    id: 'accessory-9',
    name: 'Ốp lưng UAG Pathfinder MagSafe cho iPhone 16 Pro Max',
    brand: 'UAG',
    category: 'Phụ kiện',
    imageSlug: 'acc-uag-pathfinder',
    price: 1250000,
    oldPrice: 1390000,
    stock: 45,
    specifications: {
      'Loại phụ kiện': 'Ốp lưng điện thoại',
      'Chất liệu': 'Nhựa TPU + Polycarbonate chống sốc đa lớp',
      'Tiêu chuẩn độ bền': 'Chuẩn chống rơi vỡ quân đội MIL-STD 810G 516.6 (Rơi từ độ cao 5.5 mét)',
      'Tính năng': 'Vòng từ tính nam châm MagSafe tích hợp, gờ bảo vệ viền màn hình và cụm camera',
    },
  },
  {
    id: 'accessory-10',
    name: 'Vòng đeo tay thông minh Xiaomi Smart Band 9',
    brand: 'Xiaomi',
    category: 'Đồng hồ',
    imageSlug: '',
    price: 950000,
    oldPrice: 1090000,
    stock: 65,
    specifications: {
      'Loại phụ kiện': 'Thiết bị đeo thông minh',
      'Màn hình': '1.62 inch AMOLED 60Hz, Độ sáng 1200 nits',
      'Thời lượng pin': 'Lên đến 21 ngày sử dụng liên tục',
      'Tính năng': 'Đo nhịp tim, SpO2, theo dõi giấc ngủ chi tiết, hơn 150 chế độ thể thao, kháng nước 5ATM',
    },
  },
];

module.exports = { phones, accessories };
